// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVC_Project.Models;

public partial class Group
{
    public int GroupID { get; set; }

    public string GroupName { get; set; }

    public string GroupCategory { get; set; }

    public string GroupContent { get; set; }

    public int? MinAttendee { get; set; }

    public int? MaxAttendee { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? Organizer { get; set; }

    public int? OriginalActivityID { get; set; }

    public virtual ICollection<Chat> Chat { get; set; } = new List<Chat>();

    public virtual Member OrganizerNavigation { get; set; }

    public virtual MyActivity OriginalActivity { get; set; }

    public virtual ICollection<PersonalPhoto> PersonalPhoto { get; set; } = new List<PersonalPhoto>();

    public virtual ICollection<Registration> Registration { get; set; } = new List<Registration>();
}