// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Try_Photo_Upload.Models;

public partial class Photos
{
    public int PhotoId { get; set; }

    public string PhotoName { get; set; }

    public byte[] ImageData { get; set; }
}